// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCao89fR5t41j_jLkFv6dBL1IMeNoJGRo0',
    appId: '1:669682513676:web:080cbe2812fe1dfbf1fb29',
    messagingSenderId: '669682513676',
    projectId: 'mannotrobot-35bc6',
    authDomain: 'mannotrobot-35bc6.firebaseapp.com',
    storageBucket: 'mannotrobot-35bc6.firebasestorage.app',
    measurementId: 'G-7L37CB6KE2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDipWeMdKgW_ZaPPMqOZ5wXQ3q5sXkxN3A',
    appId: '1:669682513676:android:56ad05e02e0ef115f1fb29',
    messagingSenderId: '669682513676',
    projectId: 'mannotrobot-35bc6',
    storageBucket: 'mannotrobot-35bc6.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDY7hZfSEKcUippjztwEIUKJPy42THCiSg',
    appId: '1:669682513676:ios:83a047c728a8c5fdf1fb29',
    messagingSenderId: '669682513676',
    projectId: 'mannotrobot-35bc6',
    storageBucket: 'mannotrobot-35bc6.firebasestorage.app',
    iosBundleId: 'com.example.manNotRobot',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDY7hZfSEKcUippjztwEIUKJPy42THCiSg',
    appId: '1:669682513676:ios:83a047c728a8c5fdf1fb29',
    messagingSenderId: '669682513676',
    projectId: 'mannotrobot-35bc6',
    storageBucket: 'mannotrobot-35bc6.firebasestorage.app',
    iosBundleId: 'com.example.manNotRobot',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCao89fR5t41j_jLkFv6dBL1IMeNoJGRo0',
    appId: '1:669682513676:web:0b58a33a11867adbf1fb29',
    messagingSenderId: '669682513676',
    projectId: 'mannotrobot-35bc6',
    authDomain: 'mannotrobot-35bc6.firebaseapp.com',
    storageBucket: 'mannotrobot-35bc6.firebasestorage.app',
    measurementId: 'G-L2JKBMNLHC',
  );
}
